In [43]:
import pandas as pd
import numpy as np

In [44]:
df = pd.read_csv('hotel-booking-data.txt', delimiter='\t')
df.head()

         Date Company        Person Name  Room number
0  1-Jan-2022  Avamba  Anatole Ridehalgh       4008.0
1  1-Jan-2022    Fatz    Aldrich McKevin       2002.0
2  1-Jan-2022   Leexo    Stanley Hadrill       4012.0
3      Hotels     NaN                NaN          NaN
4  1-Jan-2022  Rhyzio       Lyndell Tice       1006.0

In [45]:
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
Room number,153.0,3079.326797,1718.791186,1001.0,2001.0,3008.0,4010.0,7002.0

In [46]:
df['Company'].value_counts()

Company
Leexo           3
Quinu           3
Fivechat        3
Eadel           2
Jayo            2
               ..
Twitterwire     1
Skiba           1
Tagpad          1
Innojam         1
Twitterworks    1
Name: count, Length: 114, dtype: int64

In [47]:
df['2xRoom'] = df['Room number'] * 2

In [48]:
df

           Date       Company        Person Name  Room number   2xRoom
0    1-Jan-2022        Avamba  Anatole Ridehalgh       4008.0   8016.0
1    1-Jan-2022          Fatz    Aldrich McKevin       2002.0   4004.0
2    1-Jan-2022         Leexo    Stanley Hadrill       4012.0   8024.0
3        Hotels           NaN                NaN          NaN      NaN
4    1-Jan-2022        Rhyzio       Lyndell Tice       1006.0   2012.0
..          ...           ...                ...          ...      ...
190   Cleartrip           NaN                NaN          NaN      NaN
191  1-Jan-2022      Fivechat     Corabella Saye       4008.0   8016.0
192  1-Jan-2022       Innojam  Leandra Potapczuk       5002.0  10004.0
193  1-Jan-2022  Twitterworks    Valentia Ledson       1010.0   2020.0
194      Hotels           NaN                NaN          NaN      NaN

[195 rows x 5 columns]

In [49]:
df['Room number'].isna()

0      False
1      False
2      False
3       True
4      False
       ...
190     True
191    False
192    False
193    False
194     True
Name: Room number, Length: 195, dtype: bool

In [50]:
mask = df['Room number'].isna()
df['Text Value'] = np.where(mask, df["Date"], np.nan)
df

,Date,Company,Person Name,Room number,2xRoom,Text Value
0,1-Jan-2022,Avamba,Anatole Ridehalgh,4008.0,8016.0,NaN
1,1-Jan-2022,Fatz,Aldrich McKevin,2002.0,4004.0,NaN
2,1-Jan-2022,Leexo,Stanley Hadrill,4012.0,8024.0,NaN
3,Hotels,NaN,NaN,NaN,NaN,Hotels
4,1-Jan-2022,Rhyzio,Lyndell Tice,1006.0,2012.0,NaN
...,...,...,...,...,...,...
190,Cleartrip,NaN,NaN,NaN,NaN,Cleartrip
191,1-Jan-2022,Fivechat,Corabella Saye,4008.0,8016.0,NaN
192,1-Jan-2022,Innojam,Leandra Potapczuk,5002.0,10004.0,NaN
193,1-Jan-2022,Twitterworks,Valentia Ledson,1010.0,2020.0,NaN
194,Hotels,NaN,NaN,NaN,NaN,Hotels

In [51]:
df['Text Value'] = df['Text Value'].bfill()
df

,Date,Company,Person Name,Room number,2xRoom,Text Value
0,1-Jan-2022,Avamba,Anatole Ridehalgh,4008.0,8016.0,Hotels
1,1-Jan-2022,Fatz,Aldrich McKevin,2002.0,4004.0,Hotels
2,1-Jan-2022,Leexo,Stanley Hadrill,4012.0,8024.0,Hotels
3,Hotels,NaN,NaN,NaN,NaN,Hotels
4,1-Jan-2022,Rhyzio,Lyndell Tice,1006.0,2012.0,Booking
...,...,...,...,...,...,...
190,Cleartrip,NaN,NaN,NaN,NaN,Cleartrip
191,1-Jan-2022,Fivechat,Corabella Saye,4008.0,8016.0,Hotels
192,1-Jan-2022,Innojam,Leandra Potapczuk,5002.0,10004.0,Hotels
193,1-Jan-2022,Twitterworks,Valentia Ledson,1010.0,2020.0,Hotels
194,Hotels,NaN,NaN,NaN,NaN,Hotels

In [52]:
df.dropna(inplace=True)

In [54]:
df

,Date,Company,Person Name,Room number,2xRoom,Text Value
0,1-Jan-2022,Avamba,Anatole Ridehalgh,4008.0,8016.0,Hotels
1,1-Jan-2022,Fatz,Aldrich McKevin,2002.0,4004.0,Hotels
2,1-Jan-2022,Leexo,Stanley Hadrill,4012.0,8024.0,Hotels
4,1-Jan-2022,Rhyzio,Lyndell Tice,1006.0,2012.0,Booking
5,1-Jan-2022,Eadel,Broderic Handscombe,3015.0,6030.0,Booking
...,...,...,...,...,...,...
186,1-Jan-2022,Tagpad,Stephani Lafee,1015.0,2030.0,Expedia
187,1-Jan-2022,Meevee,Victoria Lavery,7002.0,14004.0,Expedia
191,1-Jan-2022,Fivechat,Corabella Saye,4008.0,8016.0,Hotels
192,1-Jan-2022,Innojam,Leandra Potapczuk,5002.0,10004.0,Hotels
193,1-Jan-2022,Twitterworks,Valentia Ledson,1010.0,2020.0,Hotels